In [6]:
import numpy as np
import matplotlib.pyplot as plt



In [7]:
# Step 2: Entering Dataset
n = 100  # Number of values

X1 = np.array([1, 2, 3, 4, 5])  # First independent variable
X2 = np.array([1, 4, 6, 8, 10])  # Second independent variable


In [8]:

Y = np.array([0, 0, 1, 1, 1])  # Dependent variable

# Step 3: Print X1, X2
print("X1:", X1)
print("X2:", X2)

# Step 4: Print Y
print("Y:", Y)

# Step 5: Display as array X1, X2, and Y
dataset = np.column_stack((X1, X2, Y))
print("Dataset:")
print(dataset)

# Step 6: Initialize intercept b0 = 0
b0 = 0

# Step 7: Initialize logistic coefficients b1, b2
b1 = 0
b2 = 0

# Step 8: Initialize threshold s = 0.3/0.4/0.6 any between 0 to 1 ONLY
threshold = 0.6

# Step 9: Create empty list 'p' for prediction
p = []

# Step 10: Create empty list 'pc' for prediction class
pc = []

# Step 11: Start for loop for classifying input as either '0' or '1'
for i in range(n):
    # Step 12: Append in 'p' as per the formula for logistic regression
    p_val = 1 / (1 + np.exp(-1 * (b0 + b1 * X1[i] + b2 * X2[i])))
    p.append(p_val)

    # Step 16: Apply if and else to sort/remake 'p' as per threshold
    if p_val >= threshold:
        pc.append(1)
    else:
        pc.append(0)

# Step 17: Print X1, X2 Actual Class, Prediction, Predicted Class
for i in range(n):
    print(f"X1: {X1[i]}, X2: {X2[i]}, Actual Class: {Y[i]}, Prediction: {p[i]}, Predicted Class: {pc[i]}")

# Step 18: For loop for n items.
# Step 19: Display dataset with prediction and predicted class
plt.scatter(X1, X2, c=Y, label='Actual Class')
plt.scatter(X1, X2, c=pc, marker='x', label='Predicted Class')
plt.xlabel('X1')
plt.ylabel('X2')
plt.legend()
plt.show()

X1: [1 2 3 4 5]
X2: [ 1  4  6  8 10]
Y: [0 0 1 1 1]
Dataset:
[[ 1  1  0]
 [ 2  4  0]
 [ 3  6  1]
 [ 4  8  1]
 [ 5 10  1]]


IndexError: index 5 is out of bounds for axis 0 with size 5